<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('store_product_categories')->insert([
            ['id' => 1, 'name' => 'Computer Accessories', 'code' => null],
            ['id' => 2, 'name' => 'Electric', 'code' => null],
            ['id' => 3, 'name' => 'House Keeping', 'code' => null],
            ['id' => 4, 'name' => 'Lab Product', 'code' => '00121'],
            ['id' => 5, 'name' => 'Toilatries', 'code' => null],
            ['id' => 6, 'name' => 'Diagnostic Item', 'code' => '00122'],
            ['id' => 7, 'name' => 'First Aid', 'code' => null],
            ['id' => 8, 'name' => 'Hardware', 'code' => null],
            ['id' => 9, 'name' => 'Stationary', 'code' => null],
            ['id' => 10, 'name' => 'Printing Item', 'code' => null],
            ['id' => 11, 'name' => 'Furniture', 'code' => null],
            ['id' => 12, 'name' => 'Medical Item', 'code' => null],
            ['id' => 13, 'name' => 'Electronics', 'code' => null],
            ['id' => 14, 'name' => 'Cleaning', 'code' => null],
            ['id' => 15, 'name' => 'Lab Chemical', 'code' => '002'],
            ['id' => 16, 'name' => 'Crocariz', 'code' => '005'],
            ['id' => 17, 'name' => 'Lab Device', 'code' => '00121'],
            ['id' => 18, 'name' => 'Lab Reagent', 'code' => '00122'],
            ['id' => 19, 'name' => 'Dialysis', 'code' => '00121'],
            ['id' => 20, 'name' => 'Needle', 'code' => '6565'],
            ['id' => 21, 'name' => 'Rahat H. Pharmacy', 'code' => '00121'],
        ]);

        DB::table('store_product_categories')->insert([
            ['parent_id' => 1, 'name' => 'Printer Ink', 'code' => null],
            ['parent_id' => 2, 'name' => 'Fan', 'code' => null],
            ['parent_id' => 14, 'name' => 'Wet And Dry Mop', 'code' => null],
            ['parent_id' => 14, 'name' => 'Best Bet', 'code' => null],
            ['parent_id' => 14, 'name' => 'Sterimop', 'code' => null],
            ['parent_id' => 14, 'name' => 'Wc Plus', 'code' => null],
            ['parent_id' => 14, 'name' => 'Soap', 'code' => null],
            ['parent_id' => 14, 'name' => 'Jet Powder', 'code' => null],
            ['parent_id' => 14, 'name' => 'Detergent', 'code' => null],
            ['parent_id' => 14, 'name' => 'Glass Cleaner', 'code' => null],
            ['parent_id' => 14, 'name' => 'Floor Cleaner', 'code' => null],
            ['parent_id' => 14, 'name' => 'Flower Bloom', 'code' => null],
            ['parent_id' => 2, 'name' => 'Air Cutter', 'code' => null],
            ['parent_id' => 14, 'name' => 'Bed Pan', 'code' => null],
            ['parent_id' => 14, 'name' => 'Urine Pot', 'code' => null],
            ['parent_id' => 14, 'name' => 'Plastic Bowl', 'code' => null],
            ['parent_id' => 14, 'name' => 'Backet', 'code' => null],
            ['parent_id' => 14, 'name' => 'Mug', 'code' => null],
            ['parent_id' => 14, 'name' => 'Sandel', 'code' => null],
            ['parent_id' => 14, 'name' => 'Papose', 'code' => null],
            ['parent_id' => 14, 'name' => 'Toilet Brush', 'code' => null],
            ['parent_id' => 14, 'name' => 'Belcha', 'code' => null],
            ['parent_id' => 14, 'name' => 'Dustben', 'code' => null],
            ['parent_id' => 14, 'name' => 'Polithin', 'code' => null],
            ['parent_id' => 3, 'name' => 'Rakcin With Pillow', 'code' => null],
            ['parent_id' => 4, 'name' => 'Reagent', 'code' => null],
            ['parent_id' => 5, 'name' => 'Tissue', 'code' => null],
            ['parent_id' => 5, 'name' => 'Facial Tissue', 'code' => null],
            ['parent_id' => 5, 'name' => 'Hand Wash Pump', 'code' => null],
            ['parent_id' => 5, 'name' => 'Towel', 'code' => null],
            ['parent_id' => 5, 'name' => 'Hand Wash Rifil', 'code' => null],
            ['parent_id' => 2, 'name' => 'Light', 'code' => null],
            ['parent_id' => 5, 'name' => 'Neptuline', 'code' => null],
            ['parent_id' => 5, 'name' => 'Toilet Freshner', 'code' => null],
            ['parent_id' => 5, 'name' => 'Toilet Cleaner', 'code' => null],
            ['parent_id' => 5, 'name' => 'Badna', 'code' => null],
            ['parent_id' => 5, 'name' => 'Wheel Powder', 'code' => null],
            ['parent_id' => 6, 'name' => 'U.S.G Paper', 'code' => null],
            ['parent_id' => 6, 'name' => 'Ecgpaper', 'code' => null],
            ['parent_id' => 6, 'name' => 'Ecg Roll', 'code' => null],
            ['parent_id' => 6, 'name' => 'X-Ray Film', 'code' => null],
            ['parent_id' => 6, 'name' => 'Barium Salfat', 'code' => null],
            ['parent_id' => 6, 'name' => 'U.S.G Gel', 'code' => null],
            ['parent_id' => 6, 'name' => 'Syringe', 'code' => null],
            ['parent_id' => 6, 'name' => 'Sprite', 'code' => null],
            ['parent_id' => 6, 'name' => 'Distil Water', 'code' => null],
            ['parent_id' => 6, 'name' => 'Nidel', 'code' => null],
            ['parent_id' => 6, 'name' => 'Bandage', 'code' => null],
            ['parent_id' => 6, 'name' => 'Butter Fly', 'code' => null],
            ['parent_id' => 6, 'name' => 'Youlow Tips', 'code' => null],
            ['parent_id' => 6, 'name' => 'Blue Tips', 'code' => null],
            ['parent_id' => 6, 'name' => 'Tube', 'code' => null],
            ['parent_id' => 6, 'name' => 'Glass Slide', 'code' => null],
            ['parent_id' => 6, 'name' => 'Urice', 'code' => null],
            ['parent_id' => 6, 'name' => 'E.S.R Pipette', 'code' => null],
            ['parent_id' => 6, 'name' => 'Canula', 'code' => null],
            ['parent_id' => 6, 'name' => 'Liquid Parafin', 'code' => null],
            ['parent_id' => 6, 'name' => 'Roll Bandage', 'code' => null],
            ['parent_id' => 6, 'name' => 'Strile Gauze', 'code' => null],
            ['parent_id' => 6, 'name' => 'Bsmi Cotton', 'code' => null],
            ['parent_id' => 6, 'name' => 'Normal Saline', 'code' => null],
            ['parent_id' => 6, 'name' => 'Benidict Solution', 'code' => null],
            ['parent_id' => 6, 'name' => 'Turnicat', 'code' => null],
            ['parent_id' => 6, 'name' => 'Acid', 'code' => null],
            ['parent_id' => 6, 'name' => 'Methanol', 'code' => null],
            ['parent_id' => 6, 'name' => 'X-Ray Led Appron', 'code' => null],
            ['parent_id' => 6, 'name' => 'Blood Set', 'code' => null],
            ['parent_id' => 6, 'name' => 'Uric', 'code' => null],
            ['parent_id' => 1, 'name' => 'Toner', 'code' => null],
            ['parent_id' => 6, 'name' => 'Lab Tube', 'code' => null],
            ['parent_id' => 6, 'name' => 'Niddle', 'code' => null],
            ['parent_id' => 6, 'name' => 'Adaptor', 'code' => null],
            ['parent_id' => 6, 'name' => 'Lab Device', 'code' => null],
            ['parent_id' => 7, 'name' => 'Savlon', 'code' => null],
            ['parent_id' => 8, 'name' => 'Lock', 'code' => null],
            ['parent_id' => 8, 'name' => 'Squru Driver', 'code' => null],
            ['parent_id' => 8, 'name' => 'Citkani', 'code' => null],
            ['parent_id' => 8, 'name' => 'Tape', 'code' => null],
            ['parent_id' => 9, 'name' => 'Board File', 'code' => null],
            ['parent_id' => 9, 'name' => 'Punch Machine', 'code' => null],
            ['parent_id' => 9, 'name' => 'File', 'code' => null],
            ['parent_id' => 9, 'name' => 'Air Fresner', 'code' => null],
            ['parent_id' => 9, 'name' => 'Aerosol', 'code' => null],
            ['parent_id' => 9, 'name' => 'Fluid', 'code' => null],
            ['parent_id' => 9, 'name' => 'Pen', 'code' => null],
            ['parent_id' => 9, 'name' => 'Pencil', 'code' => null],
            ['parent_id' => 9, 'name' => 'Double A Paper', 'code' => null],
            ['parent_id' => 9, 'name' => 'Photo Paper', 'code' => null],
            ['parent_id' => 9, 'name' => 'Register Book', 'code' => null],
            ['parent_id' => 9, 'name' => 'Clip File', 'code' => null],
            ['parent_id' => 9, 'name' => 'Pen Stand', 'code' => null],
            ['parent_id' => 9, 'name' => 'Stapler', 'code' => null],
            ['parent_id' => 9, 'name' => 'Scisser', 'code' => null],
            ['parent_id' => 9, 'name' => 'Scale', 'code' => null],
            ['parent_id' => 9, 'name' => 'Pin Remover', 'code' => null],
            ['parent_id' => 9, 'name' => 'Marker', 'code' => null],
            ['parent_id' => 9, 'name' => 'Bord Marker', 'code' => null],
            ['parent_id' => 9, 'name' => 'Erasor', 'code' => null],
            ['parent_id' => 9, 'name' => 'Sharpner', 'code' => null],
            ['parent_id' => 9, 'name' => 'Strapler Pin', 'code' => null],
            ['parent_id' => 9, 'name' => 'Stapler Pin', 'code' => null],
            ['parent_id' => 9, 'name' => 'Anti Cutter', 'code' => null],
            ['parent_id' => 9, 'name' => 'Gum Tube', 'code' => null],
            ['parent_id' => 9, 'name' => 'Calculator', 'code' => null],
            ['parent_id' => 9, 'name' => 'Paper Wait', 'code' => null],
            ['parent_id' => 9, 'name' => 'Binder', 'code' => null],
            ['parent_id' => 9, 'name' => 'Duster', 'code' => null],
            ['parent_id' => 9, 'name' => 'Carbon Paper', 'code' => null],
            ['parent_id' => 9, 'name' => 'Water Sponge', 'code' => null],
            ['parent_id' => 9, 'name' => 'Jems Clip', 'code' => null],
            ['parent_id' => 9, 'name' => 'Signature Pen', 'code' => null],
            ['parent_id' => 9, 'name' => 'Offset Paper', 'code' => null],
            ['parent_id' => 9, 'name' => 'Ring File', 'code' => null],
            ['parent_id' => 9, 'name' => 'Cover File', 'code' => null],
            ['parent_id' => 9, 'name' => 'Bettery', 'code' => null],
            ['parent_id' => 9, 'name' => 'Stamp Pad', 'code' => null],
            ['parent_id' => 9, 'name' => 'Tabile Basket', 'code' => null],
            ['parent_id' => 9, 'name' => 'Dusbin', 'code' => null],
            ['parent_id' => 9, 'name' => 'Hanger', 'code' => null],
            ['parent_id' => 9, 'name' => 'Antry Cutter Blade', 'code' => null],
            ['parent_id' => 9, 'name' => 'Threat', 'code' => null],
            ['parent_id' => 9, 'name' => 'Box File', 'code' => null],
            ['parent_id' => 9, 'name' => 'Bomra', 'code' => null],
            ['parent_id' => 9, 'name' => 'Register', 'code' => null],
            ['parent_id' => 10, 'name' => 'Treatment Sheet', 'code' => null],
            ['parent_id' => 10, 'name' => 'Nephrotic Chart', 'code' => null],
            ['parent_id' => 10, 'name' => 'Medicine Chart', 'code' => null],
            ['parent_id' => 10, 'name' => 'Diabetic Chart', 'code' => null],
            ['parent_id' => 10, 'name' => 'Oparation Note', 'code' => null],
            ['parent_id' => 10, 'name' => 'History Sheet', 'code' => null],
            ['parent_id' => 10, 'name' => 'Intake-Output Chart', 'code' => null],
            ['parent_id' => 10, 'name' => 'Discharge Certificate', 'code' => null],
            ['parent_id' => 10, 'name' => 'Pad', 'code' => null],
            ['parent_id' => 10, 'name' => 'Nebulization', 'code' => null],
            ['parent_id' => 10, 'name' => 'Dressing Chart', 'code' => null],
            ['parent_id' => 10, 'name' => 'Blood Transfusion', 'code' => null],
            ['parent_id' => 10, 'name' => 'Consultantvisiting Form', 'code' => null],
            ['parent_id' => 10, 'name' => 'Admission Form', 'code' => null],
            ['parent_id' => 10, 'name' => 'Envelope', 'code' => null],
            ['parent_id' => 10, 'name' => 'Investigation', 'code' => null],
            ['parent_id' => 10, 'name' => 'Death Certificate', 'code' => null],
            ['parent_id' => 10, 'name' => 'Duty Roster', 'code' => null],
            ['parent_id' => 10, 'name' => 'Report File', 'code' => null],
            ['parent_id' => 10, 'name' => 'Sheet', 'code' => null],
            ['parent_id' => 10, 'name' => 'Kham', 'code' => null],
            ['parent_id' => 10, 'name' => 'Voucher', 'code' => null],
            ['parent_id' => 10, 'name' => 'Conveyence Bill', 'code' => null],
            ['parent_id' => 10, 'name' => 'General Exp: Bill', 'code' => null],
            ['parent_id' => 10, 'name' => 'Consent Paper', 'code' => null],
            ['parent_id' => 10, 'name' => 'Demand Note', 'code' => null],
            ['parent_id' => 10, 'name' => 'Main Demand Note', 'code' => null],
            ['parent_id' => 10, 'name' => 'Silip Pad', 'code' => null],
            ['parent_id' => 10, 'name' => 'X-Stand', 'code' => null],
            ['parent_id' => 2, 'name' => 'Cable', 'code' => null],
            ['parent_id' => 2, 'name' => 'Socket', 'code' => null],
            ['parent_id' => 1, 'name' => 'Key Board', 'code' => null],
            ['parent_id' => 2, 'name' => 'Switch', 'code' => null],
            ['parent_id' => 2, 'name' => 'Regulater', 'code' => null],
            ['parent_id' => 2, 'name' => 'Cover', 'code' => null],
            ['parent_id' => 2, 'name' => 'Plug', 'code' => null],
            ['parent_id' => 2, 'name' => 'Drill Bolt', 'code' => null],
            ['parent_id' => 1, 'name' => 'Mouse', 'code' => null],
            ['parent_id' => 2, 'name' => 'Tala', 'code' => null],
            ['parent_id' => 2, 'name' => 'Connector', 'code' => null],
            ['parent_id' => 2, 'name' => 'Castap', 'code' => null],
            ['parent_id' => 2, 'name' => 'Pipe', 'code' => null],
            ['parent_id' => 2, 'name' => 'Catout', 'code' => null],
            ['parent_id' => 2, 'name' => 'Circute Braker', 'code' => null],
            ['parent_id' => 1, 'name' => 'Mouse Pad', 'code' => null],
            ['parent_id' => 2, 'name' => 'TI', 'code' => null],
            ['parent_id' => 2, 'name' => 'Electric Meter', 'code' => null],
            ['parent_id' => 11, 'name' => 'Plastic Tool', 'code' => null],
            ['parent_id' => 12, 'name' => 'Bp Machine', 'code' => null],
            ['parent_id' => 12, 'name' => 'Stethoscope', 'code' => null],
            ['parent_id' => 12, 'name' => 'Nebulizar Machine', 'code' => null],
            ['parent_id' => 13, 'name' => 'Clock', 'code' => null],
            ['parent_id' => 12, 'name' => 'Weight Machine', 'code' => null],
            ['parent_id' => 12, 'name' => 'Gluco Leader Machine', 'code' => null],
            ['parent_id' => 12, 'name' => 'Gluco Leader Strip', 'code' => null],
            ['parent_id' => 12, 'name' => 'Match Gluco Meter', 'code' => null],
            ['parent_id' => 12, 'name' => 'Match Glucometer Strip', 'code' => null],
            ['parent_id' => 12, 'name' => 'Tharmometer', 'code' => null],
            ['parent_id' => 12, 'name' => 'Hexisol', 'code' => null],
            ['parent_id' => 12, 'name' => 'Povisep', 'code' => null],
            ['parent_id' => 12, 'name' => 'Micropore', 'code' => null],
            ['parent_id' => 13, 'name' => 'Calling Bell', 'code' => null],
            ['parent_id' => 12, 'name' => 'Face Mask', 'code' => null],
            ['parent_id' => 12, 'name' => 'Surgon Gawn', 'code' => null],
            ['parent_id' => 12, 'name' => 'Surgon Cap', 'code' => null],
            ['parent_id' => 12, 'name' => 'Surgon Marks', 'code' => null],
            ['parent_id' => 12, 'name' => 'Nebulizar Mask', 'code' => null],
            ['parent_id' => 14, 'name' => 'Trolley', 'code' => null],
            ['parent_id' => 14, 'name' => 'Wet Mop Set', 'code' => null],
            ['parent_id' => 14, 'name' => 'Wet Mop Cotton', 'code' => null],
            ['parent_id' => 14, 'name' => 'Long Brom', 'code' => null],
            ['parent_id' => 6, 'name' => 'HBSAg Device', '01'],
            ['parent_id' => 16, 'name' => 'Crocariz', '00501'],
            ['parent_id' => 17, 'name' => 'Tube', '0012101'],
            ['parent_id' => 15, 'name' => 'LAB DEVICE', '00201'],
            ['parent_id' => 17, 'name' => 'Tips', '0013'],
            ['parent_id' => 6, 'name' => 'Others', '0101'],
            ['parent_id' => 17, 'name' => 'Others', '0014'],
            ['parent_id' => 18, 'name' => 'Lab Camical', '0012201'],
            ['parent_id' => 17, 'name' => 'Paper', '0015'],
            ['parent_id' => 17, 'name' => 'Galss', '0016'],
            ['parent_id' => 18, 'name' => 'Liquite', '0013'],
            ['parent_id' => 17, 'name' => 'Analyzer Paper', '0017'],
            ['parent_id' => 4, 'name' => 'Dialysis', '0012101'],
            ['parent_id' => 19, 'name' => 'Dialysis', '0012101'],
            ['parent_id' => 3, 'name' => 'cleaning', '01'],
            ['parent_id' => 9, 'name' => 'Tape', '01'],
            ['parent_id' => 10, 'name' => 'Hospital Bill', '01'],
            ['parent_id' => 12, 'name' => 'pulse oximeter', '01'],
            ['parent_id' => 4, 'name' => 'Lab product', '0013'],
            ['parent_id' => 3, 'name' => 'Tissu', '0101'],
            ['parent_id' => 3, 'name' => 'Bed Tissu', '0102'],
            ['parent_id' => 2, 'name' => 'Telephone coat', '01'],
            ['parent_id' => 9, 'name' => 'Battery', '0101'],
            ['parent_id' => 6, 'name' => 'Gloves', '0102'],
            ['parent_id' => 4, 'name' => 'Device', '0014'],
            ['parent_id' => 4, 'name' => 'Needle', '0015'],
            ['parent_id' => 3, 'name' => 'Hand Wash', '0103'],
            ['parent_id' => 3, 'name' => 'Sandel', '0104'],
            ['parent_id' => 9, 'name' => 'PAPER', '0102'],
            ['parent_id' => 4, 'name' => 'ANALYZER PAPER', '0016'],
            ['parent_id' => 12, 'name' => 'Halosin', '0101'],
            ['parent_id' => 12, 'name' => 'Halosin', '0102'],
            ['parent_id' => 4, 'name' => 'TIPS', '0017'],
            ['parent_id' => 4, 'name' => 'POT', '0018'],
            ['parent_id' => 4, 'name' => 'Needle(vein set)', '0019'],
            ['parent_id' => 19, 'name' => 'Syringe', '0013'],
        ]);
    }
}
