<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UomsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('uoms')->insert([
            ['name' => 'mm', 'details' => 'millimeter'],
            ['name' => 'cm', 'details' => 'centimeter'],
            ['name' => 'm', 'details' => 'meter'],
            ['name' => 'km', 'details' => 'kilometer'],
            ['name' => 'in', 'details' => 'inch'],
            ['name' => 'ft', 'details' => 'foot'],
            ['name' => 'yd', 'details' => 'yard'],
            ['name' => 'mi', 'details' => 'mile'],
            ['name' => 'mm Hg', 'details' => 'Millimeters of mercury'],
            ['name' => 'mmol', 'details' => 'Millimoles'],
            ['name' => 'oz', 'details' => 'ounce'],
            ['name' => 'lb', 'details' => 'pound'],
            ['name' => 'T', 'details' => 'ton'],
            ['name' => 'fl oz', 'details' => 'fluid ounce'],
            ['name' => 'pt', 'details' => 'pint'],
            ['name' => 'gal', 'details' => 'gallon'],
            ['name' => 'mg', 'details' => 'Milligram'],
            ['name' => 'g', 'details' => 'Gram'],
            ['name' => 'kg', 'details' => 'Kilogram'],
            ['name' => 'ml', 'details' => 'Milliliter'],
            ['name' => 'cl', 'details' => 'Centiliter'],
            ['name' => 'L', 'details' => 'Litter'],
            ['name' => 'g/dL', 'details' => 'Grams per deciliter'],
            ['name' => 'mcg', 'details' => 'Micrograms'],
            ['name' => 'mcg/L', 'details' => 'Micrograms per liter'],
            ['name' => 'mcg/dL', 'details' => 'Micrograms per deciliter'],
            ['name' => 'mcmol/L', 'details' => 'Micromoles per liter'],
            ['name' => 'mcL', 'details' => 'Microliters'],
            ['name' => 'mEq', 'details' => 'Milliequivalents'],
            ['name' => 'mg/dL', 'details' => 'Milligrams per deciliter'],
            ['name' => 'mg/L', 'details' => 'Milligrams per liter'],
            ['name' => 'fL', 'details' => 'Femtoliters'],
            ['name' => 'g/L', 'details' => 'Grams per liter'],
            ['name' => 'IU/L', 'details' => 'International units per liter'],
            ['name' => 'IU/mL', 'details' => 'International units per milliliter'],
            ['name' => 'mckat/L', 'details' => 'Microkats per liter'],
            ['name' => 'mEq/L', 'details' => 'Milliequivalents per liter'],
            ['name' => 'mIU/L', 'details' => 'Milli-international units per liter'],
            ['name' => 'mmol/L', 'details' => 'Millimoles per liter'],
            ['name' => 'mOsm/kg water', 'details' => 'Milliosmoles per kilogram of water'],
            ['name' => 'mU/g', 'details' => 'Milliunits per gram'],
            ['name' => 'mU/L', 'details' => 'Milliunits per liter'],
            ['name' => 'ng/dL', 'details' => 'Nanograms per deciliter'],
            ['name' => 'ng/L', 'details' => 'Nanograms per liter'],
            ['name' => 'ng/mL', 'details' => 'Nanograms per milliliter'],
            ['name' => 'ng/mL/hr', 'details' => 'Nanograms per milliliter per hour'],
            ['name' => 'nmol', 'details' => 'Nanomoles'],
            ['name' => 'nmol/L', 'details' => 'Nanomoles per liter'],
            ['name' => 'pg', 'details' => 'Picograms'],
            ['name' => 'pg/mL', 'details' => 'Picograms per milliliter'],
            ['name' => 'pmol/L', 'details' => 'Picomoles per liter'],
            ['name' => 'U/L', 'details' => 'Units per liter'],
            ['name' => 'U/mL', 'details' => 'Units per milliliter'],
            ['name' => 'cmm', 'details' => 'for blood total count cubic millimeter'],
            ['name' => 'erg/s', 'details' => 'ergs per second'],
            ['name' => 'Hp', 'details' => 'horsepower'],
            ['name' => 'CV', 'details' => 'cheval vapeur'],
            ['name' => 'mAh', 'details' => 'milliampere hour'],
            ['name' => 'Ah', 'details' => 'ampere hour'],
            ['name' => 'MHz', 'details' => 'Megahertz'],
            ['name' => 'KB', 'details' => 'Kilobyte'],
            ['name' => 'MB', 'details' => 'megabyte'],
            ['name' => 'GB', 'details' => 'Gigabyte'],
            ['name' => 'TB', 'details' => 'Terabyte'],
            ['name' => 'µIU/ml', 'details' => 'Micro International Unit per ML'],
            ['name' => 'Box', 'details' => 'Per Box'],
            ['name' => '%', 'details' => 'Percentage'],
            ['name' => 'fa', 'details' => 'Flat Amount'],
            ['name' => 'Pcs', 'details' => 'a piece'],
            ['name' => 'Pkt', 'details' => 'Packet'],
            ['name' => 'Pot', 'details' => 'A pot'],
            ['name' => 'Bottle', 'details' => 'A bottle'],
            ['name' => 'Sheet', 'details' => 'A Sheet'],
            ['name' => 'roll', 'details' => 'A roll of paper'],
            ['name' => 'None', 'details' => 'None measurement'],
            ['name' => 'Book', 'details' => 'Book'],
            ['name' => 'Coel', 'details' => 'Coel'],
            ['name' => 'Pair', 'details' => 'Pair'],
            ['name' => 'Set', 'details' => 'Set'],
            ['name' => '/HPF', 'details' => 'Per Focus'],
            ['name' => 'Flex', 'details' => 'Reagent'],
            ['name' => 'mm in 1st hr', 'details' => 'mm in 1st hr'],
            ['name' => '/cmm', 'details' => 'centimeter'],
            ['name' => 'm/ ul', 'details' => 'Mul'],
            ['name' => 'ml/min', 'details' => 'per ml meter of minute'],
        ]);
    }
}
